// generated by scripts/calibrate-flip-budget.ts — do not edit by hand
//
// Re-run `npm run calibrate:flip-budget` whenever:
//   - jsqr is upgraded (its decode tolerance shifted)
//   - The renderer pipeline changes meaningfully (Phase 2 readback semantics
//     changed, kernel tuning shifted, etc.)
//   - The set of shipped templates expands or contracts in a way that biases
//     the corpus distribution.
//
// Generated at: 2026-05-08T04:18:01.762Z

import type { ArtUpCoefficients } from './flipBudget';

/** Logistic-regression coefficients fitted from the corpus. */
export const ART_UP_COEFFICIENTS: ArtUpCoefficients = {
  intercept: 0.000000,
  surroundContrast: 0.000000,
  centreCorrelation: 0.000000,
  finderDistance: 0.000000,
};

/** Cumulative-failure tolerance for the probabilistic policy. */
export const DEFAULT_FAILURE_TOLERANCE = 1.000000;

/** Goodness-of-fit AUC. < 0.85 means ART-UP is not pulling its weight —
 *  callers should default to the 'fixed' policy. */
export const CALIBRATION_AUC = 0.676252;
